import { Check } from 'lucide-react';
import type { SavedReview } from '../core/types';
import { FOCUS_LABELS } from '../core/fixtures';
import { reviewSummary } from '../core/review';
import { Arrow, Progress } from './Chrome';
export function Completion({ saved, onExplore, onBack }: { saved: SavedReview; onExplore: () => void; onBack: () => void }) {
  const guidance = { 'entry-check': 'Before opening a position, pause to check the time and the positions already opened today.', 'daily-limit': 'Keep your daily allowance visible. Partial fills belong to the same position.', later: 'You can come back to this review when you are ready to choose a focus.' };
  return <main id="content" className="completion page-enter"><Progress current={3} /><div className="completion-check"><Check size={38} aria-hidden="true" /></div><h1 tabIndex={-1}>{saved.focus === 'later' ? 'A little clarity. A fresh start.' : 'One small step, ready for next time.'}</h1><p>Your review and rule snapshot are saved in this browser.</p><section className="saved-focus"><span>Your next step</span><h2>{FOCUS_LABELS[saved.focus]}</h2><p>{guidance[saved.focus]}</p></section><details className="saved-details"><summary>See my saved review</summary><p>{reviewSummary(saved.review).title}</p><p>{saved.review.rules.maxPositions} positions per day · before {saved.review.rules.cutoff} IST · {saved.review.session.recordsComplete ? 'Complete sample' : 'Incomplete daily records'}</p><p>{saved.review.rules.comparison === 'hypothetical' ? 'Comparison against sample history.' : 'Original sample plan.'} Saved {new Date(saved.savedAt).toLocaleString('en-GB', { timeZone: 'Asia/Kolkata' })} IST.</p></details><div className="center-actions"><button className="primary" onClick={onExplore}>Explore another review <Arrow /></button><button className="back" onClick={onBack}>Back to this session</button></div><p className="page-footnote">Local to this browser. No account, upload or live trading.</p></main>;
}
